/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
	name: 'Hello World',
	description: 'Basic Service Sample',
	sources: [{
		location: '/template-hello-world/service.mjs.template',
		action: 'copy',
		rename: '{{fileName}}.mjs'
	}],
	parameters: [],
	order: 0,
});
