/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.components.intent.generator.generates;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.eclipse.dirigible.components.base.helpers.JsonHelper;
import org.eclipse.dirigible.components.intent.LoggedValue;
import org.eclipse.dirigible.components.intent.generator.GeneratesBootstrap;
import org.eclipse.dirigible.components.intent.generator.GeneratesGuardSupport;
import org.eclipse.dirigible.components.intent.generator.IntentGenerationContext;
import org.eclipse.dirigible.components.intent.generator.IntentNaming;
import org.eclipse.dirigible.components.intent.generator.IntentTargetGenerator;
import org.eclipse.dirigible.components.intent.model.GeneratesIntent;
import org.eclipse.dirigible.components.intent.model.IntentModel;
import org.eclipse.dirigible.components.intent.model.PromptFieldIntent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

/**
 * Materializes the <b>client half</b> of each {@code generates} (create-from) action: a
 * contribution to the app's {@code <project>-custom-action} extension point - one
 * {@code <name>-generate-action.extension} plus one {@code <name>-generate-action.js} (the action
 * descriptor). Unlike a plain {@link org.eclipse.dirigible.components.intent.model.ActionIntent}
 * the descriptor carries an {@code endpoint} (not a {@code page}): the shared {@code customActions}
 * store POSTs the selected record's id to that endpoint and toasts the result rather than opening a
 * dialog.
 *
 * <p>
 * The endpoint is the REST {@code @Controller} generated (server half) from the {@code .glue}
 * file's {@code generates} collection by the {@code template-application-events-java} template,
 * served under {@code /services/java/<project>/gen/events/<module>/<ClassName>Generate/run}
 * (mirroring the inbound webhook URL layout).
 *
 * <p>
 * Idempotent: identical input always produces byte-identical output. The {@code .extension} files
 * are intent-owned (see
 * {@link org.eclipse.dirigible.components.intent.generator.IntentGenerationService}), so a
 * generates action removed from the intent is scrubbed on the next Generate.
 */
@Component
@Order(460)
public class GeneratesIntentGenerator implements IntentTargetGenerator {

    private static final Logger LOGGER = LoggerFactory.getLogger(GeneratesIntentGenerator.class);

    @Override
    public String name() {
        return "generates";
    }

    @Override
    public void generate(IntentGenerationContext context) {
        IntentModel model = context.getModel();
        if (model.getGenerates()
                 .isEmpty()) {
            return;
        }
        String project = context.getProjectName();
        for (GeneratesIntent g : model.getGenerates()) {
            String name = g.getName();
            if (name == null || name.isBlank()) {
                LOGGER.warn("Skipping generates action with no name");
                continue;
            }
            if (GeneratesBootstrap.skipped(g, model, context)) {
                // The bootstrap pass of a mutual cross-model cycle (dirigible #6539) left the server
                // controller out, so the button must go with it: a descriptor whose endpoint does not
                // exist is a click that 404s. The glue generator already reported the skip.
                LOGGER.debug("Generates action [{}] is skipped by the bootstrap pass - contributing no client action",
                        LoggedValue.of(name));
                continue;
            }
            if (!g.hasButton()) {
                // Event-driven only (issue #6711): the create-from runs by itself, so there is no button
                // to contribute - and contributing one anyway would offer the user a click that only
                // re-reads the document the event already created.
                LOGGER.debug("Generates action [{}] is event-driven with no button - contributing no client action", LoggedValue.of(name));
                continue;
            }
            String fileBase = name + "-generate-action";
            String modulePath = project + "/" + fileBase + ".js";
            // The button renders on the SOURCE entity's view, so it must be contributed to the
            // custom-action point that view reads. For a cross-model source (`fromUses:`) that view is
            // generated by the OWNER project, whose point is <owner>-custom-action - contributing to our
            // own point would emit a descriptor no view ever fetches. The descriptor file itself still
            // lives in this project; only the point it registers on belongs to the owner.
            String actionPoint = g.isCrossModelSource() ? resolveProject(model, g.getFromUses()) : project;
            context.writeModelFile(fileBase + ".extension", buildExtensionJson(project, actionPoint, modulePath, g));
            context.writeModelFile(fileBase + ".js",
                    buildDescriptorModule(project, IntentNaming.javaModule(context), g,
                            IntentNaming.customActionTranslationKey(project, context, name),
                            GeneratesGuardSupport.of(g, GeneratesGuardSupport.statusProperty(g, model, context))));
        }
    }

    /** The project owning a {@code uses:} alias (its {@code project:}, defaulting to the alias). */
    private static String resolveProject(IntentModel model, String alias) {
        for (org.eclipse.dirigible.components.intent.model.UsesIntent uses : model.getUses()) {
            if (alias.equals(uses.getModel())) {
                return uses.resolveProject();
            }
        }
        return alias; // parser rejects an undeclared alias; fall back to the convention
    }

    private static String buildExtensionJson(String project, String actionPoint, String modulePath, GeneratesIntent g) {
        Map<String, Object> extension = new LinkedHashMap<>();
        extension.put("module", modulePath);
        extension.put("extensionPoint", actionPoint + "-custom-action");
        extension.put("description", "Generate action [" + g.getName() + "] on [" + g.getForEntity() + "]"
                + (g.isCrossModelSource() ? " (contributed from [" + project + "])" : ""));
        return JsonHelper.toJson(extension);
    }

    private static String buildDescriptorModule(String project, String javaModule, GeneratesIntent g, String translationKey,
            GeneratesGuardSupport.Guard guard) {
        Map<String, Object> view = new LinkedHashMap<>();
        view.put("id", project + "-" + g.getForEntity() + "-" + g.getName());
        String label = IntentNaming.customActionLabel(g.getName(), g.getLabel());
        view.put("label", label);
        // The renderer shows T(translation.key, label) - untranslated apps keep the raw label.
        view.put("translation", Map.of("key", translationKey));
        // The server controller (server half) is served under gen/events; NOT the entity api base.
        view.put("endpoint", "/services/java/" + project + "/gen/events/" + javaModule + "/" + IntentNaming.pascalIdentifier(g.getName())
                + "Generate/run");
        view.put("view", g.getForEntity());
        view.put("type", g.getScope());
        if (g.getIcon() != null && !g.getIcon()
                                     .isBlank()) {
            view.put("icon", g.getIcon());
        }
        if (g.getOrder() != null) {
            view.put("order", g.getOrder());
        }
        if (guard != null) {
            // The from-status guard (issue #7068): the button stops offering itself on a record the
            // action would refuse - a proforma already INVOICED must not carry a live "Generate
            // Invoice". The descriptor carries the source's status FK and the ids, so the shared
            // customActions store decides it from the record it already has, with no extra request;
            // the generated controller's 409 stays the contract for every other caller.
            Map<String, Object> gate = new LinkedHashMap<>();
            gate.put("property", guard.statusProperty());
            if (!guard.allowed()
                      .isEmpty()) {
                gate.put("allowed", guard.allowed());
            } else {
                gate.put("blocked", guard.blocked());
            }
            view.put("guard", gate);
        }
        if (g.hasPrompt()) {
            // Declared input form (issue #6685): the customActions store opens a dialog instead of the
            // plain confirm, rendering one control per entry. The descriptor carries only the authored
            // names (PascalCased to the generated property names) - control types, lookups and
            // dependsOn metadata are resolved AT RUNTIME from the target's own detail registration
            // (App.detailsFor(view)), so the intent layer never references template-owned routes.
            List<Map<String, Object>> prompt = new ArrayList<>();
            for (PromptFieldIntent p : g.getPrompt()) {
                if (p.getField() == null || p.getField()
                                             .isBlank()) {
                    continue;
                }
                Map<String, Object> entry = new LinkedHashMap<>();
                entry.put("name", IntentNaming.pascalCase(p.getField()));
                entry.put("required", p.isRequired());
                prompt.add(entry);
            }
            view.put("prompt", prompt);
            view.put("promptEntity", g.getTo());
        }
        // A CommonJS module exporting getView() - the shape the extension-services endpoint loads.
        return "const viewData = " + JsonHelper.toJson(view) + ";\n" + "if (typeof exports !== 'undefined') {\n"
                + "    exports.getView = () => viewData;\n" + "}\n";
    }
}
