/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export function getSources(parameters) {
	return [
		// Location: "gen/{{genFolderName}}/ui/perspective/list"
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-window/controller.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/controller.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-window/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/index.html",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-window/view.extension.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/view.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-window/view.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/view.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-filter/controller.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/controller.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-filter/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/index.html",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-filter/view.extension.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/view.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-filter/view.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/view.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/controller.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/controller.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/index.html",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/view.extension.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/view.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/view.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/view.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-print/controller.js.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/controller.js",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-print/index.html.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/index.html",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-print/print.extension.template",
			action: "generate",
			engine: "velocity",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/print.extension",
			collection: "generateReportModels"
		},
		{
			location: "/template-application-ui-angular-v2/ui/perspective/report/dialog-print/print.js.template",
			action: "generate",
			rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/print.js",
			collection: "generateReportModels"
		}];
};
