/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as listTemplate from "template-application-ui-angular-v2/template/ui/list";
import * as manageTemplate from "template-application-ui-angular-v2/template/ui/manage";
import * as masterDetailsListTemplate from "template-application-ui-angular-v2/template/ui/masterDetailsList";
import * as masterDetailsManageTemplate from "template-application-ui-angular-v2/template/ui/masterDetailsManage";
import * as settingTemplate from "template-application-ui-angular-v2/template/ui/setting";
import * as reportTemplate from "template-application-ui-angular-v2/template/ui/report";
import * as reportChartTemplate from "template-application-ui-angular-v2/template/ui/reportChart";
import * as reportTableTemplate from "template-application-ui-angular-v2/template/ui/reportTable";
import * as navigation from "template-application-ui-angular-v2/template/ui/navigation";
// import * as perspective from "template-application-ui-angular-v2/template/ui/perspective";

export function getSources(parameters) {
    return [
        {
            location: "/template-application-ui-angular-v2/ui/translations.json.template",
            action: "translate",
        },
        ...listTemplate.getSources(parameters),
        ...manageTemplate.getSources(parameters),
        ...masterDetailsListTemplate.getSources(parameters),
        ...masterDetailsManageTemplate.getSources(parameters),
        ...settingTemplate.getSources(parameters),
        ...reportTemplate.getSources(parameters),
        ...reportChartTemplate.getSources(parameters),
        ...reportTableTemplate.getSources(parameters),
        ...navigation.getSources(parameters),
        //...perspective.getSources(parameters),
    ];
};