/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

/*
 * Master-detail view types — Harmonia SPA variant.
 *
 * Master entities (LIST_MASTER / MANAGE_MASTER, PRIMARY) browse on the manage list at /<Master> -
 * the same page a MANAGE entity gets, its record sheet showing the master's own fields - and open on
 * the manage form, which renders one detail panel per dependent entity at /<Master>/{id}/preview
 * and /<Master>/{id}/edit.
 *
 * Detail entities (LIST_DETAILS / MANAGE_DETAILS, DEPENDENT) do NOT get their own list
 * route; instead each emits:
 *   - a registration (<Detail>.detail.js) that calls App.registerDetail(<masterEntity>, {...})
 *     so the master's form can render a generic detailPanel for it (decoupled — masters never
 *     enumerate their details at generation time), and
 *   - a routed create/edit form (reusing the manage form templates) at /<Detail>/create and
 *     /<Detail>/{id}/edit, which the detail panel navigates to with the FK + returnTo preset.
 *
 * The detail list is filtered to its master via the generated controller's
 * `?<masterEntityId>=<id>` query (masterEntityId = the FK property; masterEntity = the master
 * entity name — both derived by ModelParameterProcessor for MANAGE_DETAILS/LIST_DETAILS entities).
 */
export function getSources(parameters) {
    // A master gets the manage list (its browse page) AND the manage form (its own routed
    // create/edit/preview, where its detail panels render).
    const master = (collection) => ([
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/list-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}ManageListPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/list-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-manage-list.html",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}FormPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-form.html",
            collection
        }
    ]);

    const detail = (collection) => ([
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/master/detail-register.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}.detail.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-page.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/js/components/pages/{{perspectiveName}}/{{name}}FormPage.js",
            collection
        },
        {
            location: "/template-application-ui-harmonia-java/ui/perspective/manage/form-view.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/views/{{perspectiveName}}/{{name}}-form.html",
            collection
        }
    ]);

    return [
        ...master("uiManageMasterModels"),
        ...master("uiListMasterModels"),
        ...detail("uiManageDetailsModels"),
        ...detail("uiListDetailsModels")
    ];
};
