/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
  name: "Cron Route Project Starter",
  description: "Apache Camel Cron Route Project Sample",
  sources: [
    {
      location: "/template-camel-cron-route/cron-route.camel.template",
      action: "generate",
      engine: "velocity",
      rename: "cron-route.camel",
    },
    {
      location: "/template-camel-cron-route/handler.ts.template",
      action: "generate",
      engine: "velocity",
      rename: "handler.ts",
    },
    {
      location: "/template-camel-cron-route/project.json",
      action: "generate",
      rename: "project.json",
    },
  ],
  parameters: [],
  order: 37,
});
