/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
  name: "Database View (Model)",
  description: "Database View Descriptor",
  sources: [
    {
      location: "/template-database-view/database.view.template",
      action: "generate",
      rename: "{{fileName}}.view",
    },
  ],
  parameters: [
    {
      name: "viewName",
      label: "View Name",
    },
  ],
  order: 41,
});
