/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * notifications store — the shell's in-app notification list behind the top-right bell. App code /
 * glue pushes entries via Alpine.store('notifications').add({ title, description, variant }); the
 * bell shows the unread count and the dropdown lists them.
 *
 * announce({ title, description, variant }) is what code that just DID something calls: it records
 * the entry in the bell AND raises the transient toast over Harmonia's notification overlay (the
 * `toast` template every shell declares in index.html). Before it existed (dirigible #7073) the only
 * feedback path was the bell, so a refused transition and a successful one looked exactly the same
 * on screen - nothing - and the user assumed the click had worked.
 *
 * A first source is wired in: the user's actionable BPM tasks (from the processTasks store) are
 * surfaced as notifications via syncTasks() — a new task shows up here, a completed one drops off.
 * TODO (follow-up): a persistent, server-side per-user notification inbox.
 */
document.addEventListener('alpine:init', () => {
  Alpine.store('notifications', {
    items: [],   // [{ id, title, description, variant, unread }]
    _seq: 0,

    get unreadCount() { return this.items.filter(n => n.unread).length; },

    add(n) {
      n = n || {};
      this.items.unshift({
        id: n.id || ('n' + (++this._seq)),
        title: n.title || '',
        description: n.description || '',
        variant: n.variant || 'information',
        unread: true,
      });
    },

    /**
     * Record the entry in the bell AND show it as a transient toast. Use this for the OUTCOME of
     * something the user just did; plain add() stays for background arrivals (a new task) that must
     * not interrupt.
     *
     * The toast overlay is Harmonia's (`_h_notifications`, driven by the `toast` template in the
     * shell's index.html). Missing overlay / missing template is not a reason to lose the message:
     * the bell entry is written first, so the worst case is the pre-#7073 behaviour rather than a
     * broken page.
     */
    announce(n) {
      n = n || {};
      this.add(n);
      const variant = n.variant || 'information';
      const text = [n.title, n.description].filter(Boolean).join(' - ');
      try {
        const toasts = window.Alpine && Alpine.store('_h_notifications');
        if (!toasts || typeof toasts.push !== 'function') return;
        // A refusal has to be READ; a success only has to be seen. Same reason the variant is
        // carried through: the overlay template picks the icon from it.
        const timeout = (variant === 'negative' || variant === 'warning') ? 12000 : 5000;
        toasts.push(undefined, 'toast', 'top-right', timeout, { message: text, variant });
      } catch (e) {
        console.warn('notifications: could not raise the toast for "' + text + '"', e);
      }
    },

    markAllRead() { this.items.forEach(n => { n.unread = false; }); },
    remove(id) { this.items = this.items.filter(n => n.id !== id); },
    clear() { this.items = []; },

    // Reconcile task-derived notifications against the current BPM tasks (called by processTasks):
    // keep app-pushed items and still-pending task items (preserving their read state), drop tasks
    // that are gone, and add new tasks at the top.
    syncTasks(tasks) {
      tasks = tasks || [];
      const taskIds = new Set(tasks.map(t => 'task:' + t.id));
      const kept = this.items.filter(n => n.source !== 'task' || taskIds.has(n.id));
      // A notification's text is baked in when it is created, so a kept item is re-titled here: the
      // task catalogs load asynchronously and may well not have been there when it first arrived.
      kept.forEach(n => { if (n.source === 'task' && n.task) Object.assign(n, this.taskItemText(n.task)); });
      const existing = new Set(kept.map(n => n.id));
      const added = [];
      tasks.forEach(t => {
        const id = 'task:' + t.id;
        if (!existing.has(id)) {
          added.push(Object.assign({
            id,
            source: 'task',
            task: t,
            variant: 'information',
            unread: true,
          }, this.taskItemText(t)));
        }
      });
      this.items = added.concat(kept);
    },

    // What a task-derived notification reads, in the user's language — the names come from the
    // processTasks store, the single place that knows how a task is named.
    taskItemText(task) {
      const tasks = Alpine.store('processTasks');
      const name = tasks ? tasks.taskName(task) : (task.name || 'Task');
      const process = tasks ? tasks.processName(task) : (task.processDefinitionName || '');
      // ... and WHICH record it is about, once the store has resolved it (#7077): "New task: Approve"
      // says nothing about which invoice is waiting.
      const subject = tasks ? tasks.subject(task) : '';
      return {
        title: window.T ? T('application-core:shell.notifications.newTask', 'New task: {{name}}', { name }) : 'New task: ' + name,
        description: subject && process ? process + ' · ' + subject : (subject || process),
      };
    },
  });
}, { once: true });
