/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * related store — "Add new <related entity>" from an FK combobox without leaving the current form.
 * An FK field's Add button calls $store.related.create(createUrl, title, onCreated); the dialog
 * (declared once in index.html) opens an iframe to the target entity's OWN generated create page
 * (App.utils.relatedCreateUrl, which works cross-model). The embedded create form posts a
 * 'harmonia.entity.created' message on save (see baseFormPage); the message listener below routes it
 * to onCreated(id), which the opener uses to refresh that field's options and select the new record.
 */
document.addEventListener('alpine:init', () => {
  Alpine.store('related', {
    open: false,
    src: '',
    title: 'Add new',
    _onCreated: null,

    // The dialog's embedded page is its one scroll container (issue #7723): while it is open the page
    // behind the overlay - its document and the shell's #app - must not scroll as well, or the user
    // sees two scrollbars and a wheel past the end of the form scrolls the page underneath. Keyed on
    // `open` itself, because the dialog is also closed by assigning it (the X button) rather than
    // through close().
    init() {
      Alpine.effect(() => lockPageScroll(this.open));
    },

    create(createUrl, title, onCreated) {
      if (!createUrl) return;
      this.src = createUrl;
      this.title = title || (window.T ? T('application-core:shell.related.addNew', 'Add new') : 'Add new');
      this._onCreated = typeof onCreated === 'function' ? onCreated : null;
      this.open = true;
    },

    close() {
      this.open = false;
      this.src = '';
      this._onCreated = null;
    },

    // Routed here by the global message listener when the embedded create form reports a save.
    handleCreated(id) {
      const cb = this._onCreated;
      this.close();
      if (cb) {
        try { cb(id); } catch (e) { console.error('[related] onCreated handler failed', e); }
      }
    },
  });
});

// The page's scroll containers' own overflow while the dialog holds them, null when it does not.
let lockedScroll = null;

// Stop (true) or restore (false) the scrolling of the page behind the dialog. Each container gets
// back the inline overflow it had, so a page that set its own keeps it; overflow:hidden keeps the
// scroll position, so the user returns to where they were.
function lockPageScroll(lock) {
  if (lock && !lockedScroll) {
    lockedScroll = [document.documentElement, document.getElementById('app')]
      .filter(Boolean)
      .map((element) => ({ element, overflow: element.style.overflow }));
    lockedScroll.forEach(({ element }) => { element.style.overflow = 'hidden'; });
  } else if (!lock && lockedScroll) {
    lockedScroll.forEach(({ element, overflow }) => { element.style.overflow = overflow; });
    lockedScroll = null;
  }
}

// The embedded form posts a message to its parent: 'harmonia.entity.created' (with id) when a
// create saves, 'harmonia.entity.updated' when a detail-panel dialog's edit saves, or
// 'harmonia.dialog.cancel' when the user cancels. Created and updated take the same path - close
// the dialog and hand the id to the opener's callback (select the new record / reload the panel).
window.addEventListener('message', (event) => {
  const data = event && event.data;
  if (!data) return;
  try {
    const store = window.Alpine && Alpine.store('related');
    if (!store || !store.open) return;
    if (data.type === 'harmonia.entity.created' || data.type === 'harmonia.entity.updated') store.handleCreated(data.id);
    else if (data.type === 'harmonia.dialog.cancel') store.close();
  } catch (e) { /* Alpine not ready / no store */ }
});
