/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors
 * SPDX-License-Identifier: EPL-2.0
 */
/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * theme store — the shell's colour-scheme control (light | dark | auto). A global store (not a
 * component property) so the toolbar control resolves from any scope. Backed by Harmonia's
 * colour-scheme API: `mode` is the user's selection - Harmonia persists it to the shared
 * `codbex.harmonia.colorMode` key, applies the `.dark` class and keeps every same-origin frame and
 * browser tab in sync itself - and `scheme` is what is on screen right now (`auto` resolved against
 * the OS). The colour-scheme listener keeps both in step when the change is made elsewhere: another
 * frame, another tab, or the OS flipping while `auto` is selected.
 */
document.addEventListener('alpine:init', () => {
  Alpine.store('theme', {
    _mode: 'auto',    // 'light' | 'dark' | 'auto' — the selection
    scheme: 'light',  // 'light' | 'dark' — the scheme applied right now

    init() {
      if (!window.Harmonia) return;
      this._mode = Harmonia.getColorScheme();
      this.scheme = this.resolve(this._mode);
      Harmonia.addColorSchemeListener((scheme, mode) => {
        this.scheme = scheme;
        if (mode) this._mode = mode;
      });
    },

    get mode() { return this._mode; },

    set mode(value) {
      if (value !== 'light' && value !== 'dark' && value !== 'auto') return;
      this._mode = value;
      this.scheme = this.resolve(value);
      if (window.Harmonia) Harmonia.setColorScheme(value);
    },

    // The toolbar control's icon: the selection when it is explicit, the resolved scheme otherwise.
    get icon() {
      if (this._mode === 'auto') return 'sun-moon';
      return this.scheme === 'dark' ? 'moon' : 'sun';
    },

    resolve(mode) {
      if (mode === 'light' || mode === 'dark') return mode;
      return window.Harmonia ? Harmonia.getSystemColorScheme() : 'light';
    },
  });
}, { once: true });
