/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
  name: "Data Tables (UI)",
  description: "Table View With HTTP Data Requests",
  image: "/services/web/template-html/template.svg",
  sources: [
    {
      location: "/template-html/index.html.template",
      action: "generate",
      rename: "{{fileName}}.html",
      start: "[[",
      end: "]]",
    },
  ],
  parameters: [],
  order: 30,
});
