/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.components.ide.template.service.model;

import org.eclipse.dirigible.commons.api.helpers.NamingHelper;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.eclipse.dirigible.components.ide.template.service.model.ModelValues.asMap;
import static org.eclipse.dirigible.components.ide.template.service.model.ModelValues.asMaps;
import static org.eclipse.dirigible.components.ide.template.service.model.ModelValues.defaultRole;
import static org.eclipse.dirigible.components.ide.template.service.model.ModelValues.str;
import static org.eclipse.dirigible.components.ide.template.service.model.ModelValues.strOr;
import static org.eclipse.dirigible.components.ide.template.service.model.ModelValues.truthy;

/**
 * Prepares a model and its parameters for one template.
 *
 * <p>
 * A template descriptor declares only <em>what</em> to render; the preparation each template needs
 * before its sources are rendered - which node of the model file to generate from, and the derived
 * parameters its sources reference - is per-template knowledge, and this is where it lives.
 *
 * <p>
 * A template the pipeline does not know is refused by name rather than generated incompletely.
 */
final class ModelTemplateAdapters {

    /** The default brand icon of a generated application. */
    private static final String DEFAULT_APP_ICON = "blocks";

    /** The default data language of a generated application. */
    private static final String DEFAULT_APP_LANGUAGE = "en";

    /**
     * Not instantiable.
     */
    private ModelTemplateAdapters() {}

    /**
     * A model prepared for generation.
     *
     * @param model the node to generate from
     * @param entityShaped whether the node is an entity model, which selects the entity pipeline
     */
    record PreparedModel(Map<String, Object> model, boolean entityShaped) {
    }

    /** The preparation of each supported template, keyed by its module path. */
    private static final Map<String, Adapter> ADAPTERS = Map.of(//
            "template-application-schema/template/template.js", ModelTemplateAdapters::entityModel, //
            "template-application-dao-java/template/template.js", ModelTemplateAdapters::entityModel, //
            "template-application-rest-java/template/template.js", ModelTemplateAdapters::entityModel, //
            "template-application-ui-harmonia-java/template/template.js", ModelTemplateAdapters::harmoniaApplication, //
            "template-application-events-java/template/template.js", ModelTemplateAdapters::glue, //
            "template-application-ui-harmonia-java/template/template-report-file.js", ModelTemplateAdapters::report, //
            "template-form-builder-harmonia/template/template.js", (modelText, parameters) -> form(modelText), //
            "template-mapping-javascript/template/template.js", (modelText, parameters) -> mapping(modelText), //
            "template-mapping-java/template/template.js", ModelTemplateAdapters::javaMapping);

    /**
     * Prepares a model for a template.
     *
     * @param templateId the template's module path, as the request names it
     * @param modelText the raw model file
     * @param parameters the generation parameters, mutated with the template's derived parameters
     * @return the prepared model
     * @throws IllegalArgumentException when the template has no Java preparation
     */
    static PreparedModel prepare(String templateId, String modelText, Map<String, Object> parameters) {
        Adapter adapter = ADAPTERS.get(templateId);
        if (adapter == null) {
            throw new IllegalArgumentException("Template [" + templateId + "] is not supported by the Java model-generation pipeline.");
        }
        return adapter.prepare(modelText, parameters);
    }

    /**
     * Tests whether a template can be generated by the Java pipeline.
     *
     * @param templateId the template's module path
     * @return true when it is supported
     */
    static boolean supports(String templateId) {
        return ADAPTERS.containsKey(templateId);
    }

    /**
     * The preparation of one template.
     */
    @FunctionalInterface
    private interface Adapter {

        /**
         * Prepares a model.
         *
         * @param modelText the raw model file
         * @param parameters the generation parameters
         * @return the prepared model
         */
        PreparedModel prepare(String modelText, Map<String, Object> parameters);
    }

    /**
     * Prepares a plain entity model - the schema, DAO and REST layers.
     *
     * @param modelText the raw model file
     * @param parameters the generation parameters
     * @return the prepared model
     */
    private static PreparedModel entityModel(String modelText, Map<String, Object> parameters) {
        Map<String, Object> model = entityRoot(modelText);
        ModelParameterProcessor.process(model, parameters);
        return new PreparedModel(model, true);
    }

    /**
     * Prepares the full application stack, whose UI needs the application's own caption, icon,
     * languages and dashboard widgets.
     *
     * @param modelText the raw model file
     * @param parameters the generation parameters
     * @return the prepared model
     */
    private static PreparedModel harmoniaApplication(String modelText, Map<String, Object> parameters) {
        Map<String, Object> model = entityRoot(modelText);
        parameters.put("javaRuntime", Boolean.TRUE);
        ModelParameterProcessor.process(model, parameters);
        // The shell's title and sidebar header prefer the model's own title and description over the
        // bare project name.
        parameters.put("appTitle", blankToNull(str(model, "title")) != null ? model.get("title") : parameters.get("projectName"));
        parameters.put("appDescription", strOr(model, "description", ""));
        // An explicit generate-time icon wins over the model's, which wins over a neutral default.
        String appIcon = blankToNull(str(parameters, "appIcon"));
        if (appIcon == null) {
            appIcon = blankToNull(str(model, "icon"));
        }
        parameters.put("appIcon", appIcon == null ? DEFAULT_APP_ICON : appIcon);
        // The data languages the application offers, rendered into its configuration as a JSON array.
        List<Object> languages = ModelValues.asList(model.get("languages"));
        parameters.put("appLanguages",
                JavaScriptJson.compact(languages.isEmpty() ? List.of(DEFAULT_APP_LANGUAGE) : new ArrayList<>(languages)));
        parameters.put("customWidgets", model.get("widgets") == null ? new ArrayList<>() : model.get("widgets"));
        // Country-scoped field labels, rendered into the application's configuration as a JSON object
        // the shared i18n runtime prefers over the language catalogs (see countryLabelOverlay).
        parameters.put("countryLabels", JavaScriptJson.compact(countryLabelOverlay(model, parameters)));
        return new PreparedModel(model, true);
    }

    /**
     * The application's country label overlay: the property labels that are resolved from the tenant's
     * country instead of the reader's language, as <code>{ &lt;country&gt;: { &lt;translation key&gt;:
     * &lt;label&gt; } }</code>.
     *
     * <p>
     * Keyed by the very translation key the generated views bind - {@code <project>:<tprefix>.t.<data
     * name>} - so the runtime resolves an overlay with one exact lookup and needs to know nothing about
     * how a key is composed. The overlay deliberately does NOT travel in the language catalogs: those
     * are per language and are not even loaded in the default one, which is exactly the mismatch a
     * country-scoped label suffers from (dirigible #6424).
     *
     * @param model the entity model
     * @param parameters the generation parameters, for the project name and the catalog prefix
     * @return the overlay, empty when no field declares a country label
     */
    private static Map<String, Object> countryLabelOverlay(Map<String, Object> model, Map<String, Object> parameters) {
        String namespace = str(parameters, "projectName") + ":" + ModelTranslations.catalogPrefix(str(parameters, "filePath")) + ".t.";
        Map<String, Object> overlay = new LinkedHashMap<>();
        for (Map<String, Object> entity : asMaps(model.get("entities"))) {
            for (Map<String, Object> property : asMaps(entity.get("properties"))) {
                Map<String, Object> variants = asMap(property.get("widgetCountryLabels"));
                if (variants == null || str(property, "dataName") == null) {
                    continue;
                }
                for (Map.Entry<String, Object> variant : variants.entrySet()) {
                    @SuppressWarnings("unchecked")
                    Map<String, Object> labels =
                            (Map<String, Object>) overlay.computeIfAbsent(variant.getKey(), country -> new LinkedHashMap<String, Object>());
                    labels.put(namespace + str(property, "dataName"), variant.getValue());
                }
            }
        }
        return overlay;
    }

    /**
     * Prepares a glue file. It carries no entities, so it is given an empty list - the entity pipeline
     * partitions that list up front, and every glue source names a glue collection instead.
     *
     * @param modelText the raw model file
     * @param parameters the generation parameters
     * @return the prepared model
     */
    private static PreparedModel glue(String modelText, Map<String, Object> parameters) {
        Map<String, Object> model = ModelJson.parseObject(modelText);
        if (!(model.get("entities") instanceof List)) {
            model.put("entities", new ArrayList<>());
        }
        parameters.put("javaGenFolderName", NamingHelper.sanitizeJavaIdentifier(str(parameters, "genFolderName")));
        return new PreparedModel(model, true);
    }

    /**
     * Prepares a standalone report, resolving its column and parameter types and pre-escaping its query
     * for the generated repository.
     *
     * @param modelText the raw model file
     * @param parameters the generation parameters
     * @return the prepared model
     */
    private static PreparedModel report(String modelText, Map<String, Object> parameters) {
        Map<String, Object> model = ModelJson.parseObject(modelText);
        for (Map<String, Object> column : asMaps(model.get("columns"))) {
            ModelDataTypes.DataType dataType = ModelDataTypes.parse(str(column, "type"));
            column.put("typeJava", dataType.java());
            column.put("typeTypescript", dataType.typescript());
            if ("Date".equals(dataType.typescript())) {
                model.put("hasDates", Boolean.TRUE);
            }
            // Rendering defaults for reports authored before the column alignment and pattern
            // metadata: a numeric column right-aligns, a decimal one gets the platform money pattern.
            if (!truthy(column, "align")) {
                column.put("align", "number".equals(dataType.typescript()) ? "right" : "left");
            }
            String sqlType = strOr(column, "type", "").toUpperCase(java.util.Locale.ROOT);
            if (!truthy(column, "pattern") && ("DECIMAL".equals(sqlType) || "DOUBLE".equals(sqlType))) {
                column.put("pattern", "### ### ### ##0.00");
            }
        }
        for (Map<String, Object> parameter : asMaps(model.get("parameters"))) {
            ModelDataTypes.DataType dataType = ModelDataTypes.parse(str(parameter, "type"));
            parameter.put("typeJava", dataType.java());
            parameter.put("typeTypescript", dataType.typescript());
            // The authored fallback the parameter is bound with when the caller leaves the input empty.
            // The generated repository writes it into a Java string literal, so an apostrophe-carrying
            // value is fine but a quote or a backslash would end that literal and fail the compile of
            // the whole generated module (#7295).
            parameter.put("initialJavaLiteral", JavaLiterals.escape(strOr(parameter, "initial", "")));
            String placeholder = ":" + str(parameter, "name");
            for (Map<String, Object> condition : asMaps(model.get("conditions"))) {
                if (placeholder.equals(str(condition, "right")) && "string".equals(dataType.typescript())
                        && "LIKE".equals(str(condition, "operation"))) {
                    parameter.put("isLikeCondition", Boolean.TRUE);
                }
            }
        }
        String query = strOr(model, "query", "");
        // The report's query pre-escaped as PER-LINE Java string literals, for the generated
        // repository to join back with newlines. Deliberately never one single-line literal: a
        // multi-kilobyte escaped-quote-dense literal is exactly what overflowed the platform's
        // literal-scanning source parser and took synchronization down instance-wide (#6936) - and
        // since the heavy report kinds keep their structural SQL in a generated .view (#6938), each
        // line here stays short by construction.
        List<Object> queryJavaLines = new ArrayList<>();
        for (String line : query.split("\n", -1)) {
            queryJavaLines.add(JavaScriptJson.compact(line));
        }
        model.put("queryJavaLines", queryJavaLines);
        if (!parameters.containsKey("extensionPoint")) {
            parameters.put("extensionPoint", parameters.get("projectName"));
        }
        if (!parameters.containsKey("name")) {
            parameters.put("name", model.get("name"));
        }
        parameters.put("perspectiveName", "Reports");
        parameters.put("javaGenFolderName", NamingHelper.sanitizeJavaIdentifier(str(parameters, "genFolderName")));
        parameters.put("javaPerspectiveName", NamingHelper.sanitizeJavaIdentifier(str(parameters, "perspectiveName")));
        parameters.put("roles", reportRoles(model));
        return new PreparedModel(model, false);
    }

    /**
     * Collects the default roles a report asks to be generated - each gate's own role, its first (see
     * {@link ModelValues#defaultRole}).
     *
     * @param model the report model
     * @return the roles
     */
    private static List<Object> reportRoles(Map<String, Object> model) {
        List<Object> roles = new ArrayList<>();
        Map<String, Object> security = asMap(model.get("security"));
        if (security == null || !"true".equals(security.get("generateDefaultRoles"))) {
            return roles;
        }
        Map<String, Object> rolePair = new LinkedHashMap<>();
        rolePair.put("entityName", model.get("name"));
        String roleRead = defaultRole(security, "roleRead");
        if (roleRead != null) {
            rolePair.put("roleRead", roleRead);
        }
        String roleWrite = defaultRole(security, "roleWrite");
        if (roleWrite != null) {
            rolePair.put("roleWrite", roleWrite);
        }
        roles.add(rolePair);
        return roles;
    }

    /**
     * Prepares a form. Its code is the body of the generated controller function, so it is indented for
     * embedding.
     *
     * @param modelText the raw model file
     * @return the prepared model
     */
    private static PreparedModel form(String modelText) {
        Map<String, Object> model = ModelJson.parseObject(modelText);
        String code = str(model, "code");
        if (code != null && !code.isEmpty()) {
            StringBuilder indented = new StringBuilder(code.length() + 32);
            String[] lines = code.split("\n", -1);
            for (int i = 0; i < lines.length; i++) {
                if (i > 0) {
                    indented.append('\n');
                }
                indented.append("    ")
                        .append(lines[i]);
            }
            model.put("code", indented.toString());
        }
        return new PreparedModel(model, false);
    }

    /**
     * Prepares a mapping. The template embeds the mapping file verbatim, so the raw text is handed
     * through rather than the parsed graph.
     *
     * @param modelText the raw model file
     * @return the prepared model
     */
    private static PreparedModel mapping(String modelText) {
        Map<String, Object> model = new LinkedHashMap<>();
        model.put("mapping", modelText);
        return new PreparedModel(model, false);
    }

    /**
     * Prepares a mapping for the client-Java mapper, whose sources render the compiled column
     * expressions rather than the mapping file.
     *
     * @param modelText the raw model file
     * @param parameters the generation parameters, mutated with the mapper's package and class name
     * @return the prepared model
     */
    private static PreparedModel javaMapping(String modelText, Map<String, Object> parameters) {
        parameters.put("javaGenFolderName", NamingHelper.sanitizeJavaIdentifier(str(parameters, "genFolderName")));
        parameters.put("mapperClassName", MappingCompiler.className(str(parameters, "fileName")));
        return new PreparedModel(MappingCompiler.compile(modelText), false);
    }

    /**
     * Reads the entity model out of a model file, which wraps it under a {@code model} key.
     *
     * @param modelText the raw model file
     * @return the entity model
     */
    private static Map<String, Object> entityRoot(String modelText) {
        Map<String, Object> root = ModelJson.parseObject(modelText);
        Map<String, Object> model = asMap(root.get("model"));
        return model == null ? new LinkedHashMap<>() : model;
    }

    /**
     * Normalizes a blank string to null, for the "prefer this if it says anything" checks.
     *
     * @param value the value
     * @return the trimmed value, or null when it is absent or blank
     */
    private static String blankToNull(String value) {
        return value == null || value.isBlank() ? null : value.trim();
    }

}
