/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.integration.tests.api;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.both;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.greaterThanOrEqualTo;
import static org.hamcrest.Matchers.lessThan;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

import org.eclipse.dirigible.components.initializers.synchronizer.SynchronizationProcessor;
import org.eclipse.dirigible.repository.api.IRepository;
import org.eclipse.dirigible.repository.api.IRepositoryStructure;
import org.eclipse.dirigible.repository.api.IResource;
import org.eclipse.dirigible.tests.base.IntegrationTest;
import org.eclipse.dirigible.tests.framework.restassured.RestAssuredExecutor;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

/**
 * dirigible #7701: a {@code checks: agree} junction guards a parent owned by ANOTHER model, end to
 * end on two generated, published projects.
 *
 * <p>
 * #7626 made the junction's same-model parents refuse a change of the agreed property while a
 * junction row references them, but a cross-model parent's repository is generated by its own
 * model, which never reads the junction's declarations - so re-pointing an allocated payment to
 * another customer answered 200 and left the allocation in exactly the pairing the check refuses.
 * The direction flips as for #7657's delete rules: the junction's repository contributes an
 * {@code org.eclipse.dirigible.sdk.db.TargetAgreementRule}, and the parent's base repository asks
 * every contribution on its update paths.
 */
class IntentCrossModelAgreeGuardIT extends IntegrationTest {

    private static final String WORKSPACE = "workspace";
    /**
     * Owns the customers and the payments. Its project name differs from the model alias on purpose.
     */
    private static final String OWNER = "agree-owner";
    /** Owns the invoices and the junction allocating payments to them. */
    private static final String CONSUMER = "agree-consumer";

    private static final String OWNER_MODEL = "payments";
    private static final String CONSUMER_MODEL = "billing";

    private static final String MESSAGE = "This payment belongs to a different customer than the invoice";

    private static final String OWNER_INTENT = """
            name: payments
            description: cross-model agree fixture - the owner of the payment parent

            entities:
              - name: Customer
                fields:
                  - { name: id,   type: integer, primaryKey: true, generated: true }
                  - { name: name, type: string,  required: true, length: 100 }
              - name: CustomerPayment
                fields:
                  - { name: id,     type: integer, primaryKey: true, generated: true }
                  - { name: amount, type: decimal }
                relations:
                  - { name: Customer, kind: manyToOne, to: Customer, required: true }
            """;

    private static final String CONSUMER_INTENT = """
            name: billing
            description: cross-model agree fixture - a junction whose payment parent another model owns

            uses:
              - { model: payments, project: agree-owner }

            entities:
              - name: SalesInvoice
                fields:
                  - { name: id,     type: integer, primaryKey: true, generated: true }
                  - { name: amount, type: decimal }
                relations:
                  - { name: Customer, kind: manyToOne, to: Customer, model: payments, required: true }
              - name: InvoicePayment
                checks:
                  - { kind: agree, relations: [SalesInvoice, CustomerPayment], onProperty: Customer,
                      message: "This payment belongs to a different customer than the invoice" }
                fields:
                  - { name: id,     type: integer, primaryKey: true, generated: true }
                  - { name: amount, type: decimal }
                relations:
                  - { name: SalesInvoice,    kind: manyToOne, to: SalesInvoice, required: true }
                  - { name: CustomerPayment, kind: manyToOne, to: CustomerPayment, model: payments, required: true }
            """;

    @Autowired
    private IRepository repository;
    @Autowired
    private RestAssuredExecutor restAssuredExecutor;
    @Autowired
    private SynchronizationProcessor synchronizationProcessor;

    private String customers;
    private String payments;
    private String invoices;
    private String allocations;

    @Test
    void a_cross_model_parent_refuses_re_pointing_what_a_junction_row_relies_on() {
        writeIntent(OWNER, OWNER_INTENT);
        generateProject(OWNER);
        writeIntent(CONSUMER, CONSUMER_INTENT);
        generateProject(CONSUMER);

        String junctionRepository = contentOf(CONSUMER, "gen/" + CONSUMER_MODEL + "/data/invoicepayment/InvoicePaymentRepository.java");
        assertTrue(junctionRepository.contains("org.eclipse.dirigible.sdk.db.TargetAgreementRule"),
                "the junction's repository must contribute the guard for its cross-model parent: " + junctionRepository);

        publishProject(OWNER);
        publishProject(CONSUMER);
        synchronizationProcessor.forceProcessSynchronizers();

        String ownerApi = "/services/java/" + OWNER + "/gen/" + OWNER_MODEL + "/api";
        String consumerApi = "/services/java/" + CONSUMER + "/gen/" + CONSUMER_MODEL + "/api";
        customers = ownerApi + "/customer/CustomerController";
        payments = ownerApi + "/customerpayment/CustomerPaymentController";
        invoices = consumerApi + "/salesinvoice/SalesInvoiceController";
        allocations = consumerApi + "/invoicepayment/InvoicePaymentController";

        int acme = create(customers, "{\"Name\":\"Acme\"}");
        int globex = create(customers, "{\"Name\":\"Globex\"}");
        int payment = create(payments, "{\"Customer\":" + acme + ",\"Amount\":50}");
        int invoice = create(invoices, "{\"Customer\":" + acme + ",\"Amount\":50}");
        int allocation = create(allocations, "{\"SalesInvoice\":" + invoice + ",\"CustomerPayment\":" + payment + ",\"Amount\":50}");

        // The issue's reproduction: the allocated payment re-pointed to another customer was a 200.
        assertRefused(payments + "/" + payment, "{\"Id\":" + payment + ",\"Customer\":" + globex + ",\"Amount\":50}");
        assertField(payments + "/" + payment, "Customer", acme);
        // The same-model parent keeps its own #7626 guard.
        assertRefused(invoices + "/" + invoice, "{\"Id\":" + invoice + ",\"Customer\":" + globex + ",\"Amount\":50}");

        // Only a CHANGE of the relied-on property is refused: an edit keeping the customer saves.
        assertUpdated(payments + "/" + payment, "{\"Id\":" + payment + ",\"Customer\":" + acme + ",\"Amount\":60}");
        // An unallocated payment re-points freely.
        int other = create(payments, "{\"Customer\":" + acme + ",\"Amount\":5}");
        assertUpdated(payments + "/" + other, "{\"Id\":" + other + ",\"Customer\":" + globex + ",\"Amount\":5}");
        // With the allocation gone, nothing relies on the payment's customer any more.
        restAssuredExecutor.execute(() -> given().when()
                                                 .delete(allocations + "/" + allocation)
                                                 .then()
                                                 .statusCode(both(greaterThanOrEqualTo(200)).and(lessThan(300))));
        assertUpdated(payments + "/" + payment, "{\"Id\":" + payment + ",\"Customer\":" + globex + ",\"Amount\":60}");
        assertField(payments + "/" + payment, "Customer", globex);
    }

    private void assertRefused(String record, String body) {
        restAssuredExecutor.execute(() -> given().contentType("application/json")
                                                 .body(body)
                                                 .when()
                                                 .put(record)
                                                 .then()
                                                 .statusCode(400)
                                                 .body(containsString(MESSAGE)));
    }

    private void assertUpdated(String record, String body) {
        restAssuredExecutor.execute(() -> given().contentType("application/json")
                                                 .body(body)
                                                 .when()
                                                 .put(record)
                                                 .then()
                                                 .statusCode(200));
    }

    private void assertField(String record, String field, int value) {
        restAssuredExecutor.execute(() -> given().when()
                                                 .get(record)
                                                 .then()
                                                 .statusCode(200)
                                                 .body(field, equalTo(value)));
    }

    private int create(String controller, String body) {
        AtomicInteger id = new AtomicInteger();
        restAssuredExecutor.execute(() -> id.set(given().contentType("application/json")
                                                        .body(body)
                                                        .when()
                                                        .post(controller)
                                                        .then()
                                                        .statusCode(200)
                                                        .extract()
                                                        .path("Id")),
                60);
        return id.get();
    }

    /**
     * Generate the model files from the intent and drive model-to-code from the generate response's own
     * plan.
     */
    private void generateProject(String project) {
        AtomicReference<List<Map<String, Object>>> plan = new AtomicReference<>();
        restAssuredExecutor.execute(() -> plan.set(given().when()
                                                          .post("/services/ide/intent/generate?workspace=" + WORKSPACE + "&project="
                                                                  + project + "&path=app.intent")
                                                          .then()
                                                          .statusCode(200)
                                                          .extract()
                                                          .jsonPath()
                                                          .getList("codeGenerations")));
        for (Map<String, Object> codeGeneration : plan.get()) {
            assertEquals(Boolean.TRUE, codeGeneration.get("generated"),
                    "generating code from " + codeGeneration.get("path") + " failed: " + codeGeneration.get("error"));
        }
    }

    private void publishProject(String project) {
        restAssuredExecutor.execute(() -> given().when()
                                                 .post("/services/ide/publisher/" + WORKSPACE + "/" + project + "/")
                                                 .then()
                                                 .statusCode(200));
    }

    private void writeIntent(String project, String yaml) {
        String path = projectPath(project) + "/app.intent";
        IResource existing = repository.getResource(path);
        if (existing.exists()) {
            existing.setContent(yaml.getBytes(StandardCharsets.UTF_8));
        } else {
            repository.createResource(path, yaml.getBytes(StandardCharsets.UTF_8));
        }
    }

    private String contentOf(String project, String fileName) {
        return new String(repository.getResource(projectPath(project) + "/" + fileName)
                                    .getContent(),
                StandardCharsets.UTF_8);
    }

    private static String projectPath(String project) {
        return IRepositoryStructure.PATH_USERS + "/admin/" + WORKSPACE + "/" + project;
    }

    @AfterEach
    void cleanup() {
        for (String project : List.of(CONSUMER, OWNER)) {
            restAssuredExecutor.execute(() -> given().when()
                                                     .delete("/services/ide/publisher/" + WORKSPACE + "/" + project)
                                                     .then()
                                                     .statusCode(both(greaterThanOrEqualTo(200)).and(lessThan(300))));
            if (repository.hasCollection(projectPath(project))) {
                repository.removeCollection(projectPath(project));
            }
        }
    }
}
