/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as generateUtils from "service-generate/template/generateUtils";

export function generate(model, parameters) {
    const templateModel = {};
    templateModel.mapping = model;
    const templateSources = getTemplate(parameters).sources;
    return generateUtils.generateGeneric(templateModel, parameters, templateSources);
};

export function getTemplate(parameters) {
    return {
        name: "Generator from Mapping Model",
        description: "Mapping Model Generator Template",
        extension: "mapping",
        sources: [
            {
                location: "/template-mapping-javascript/mapper.ts.template",
                action: "generate",
                rename: "gen/{{genFolderName}}/mappings/{{fileName}}.ts",
                engine: "velocity",
            }
        ],
        parameters: []
    };
}
