/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
export const getTemplate = () => ({
  name: "Database Table (Model)",
  description: "Database Table Descriptor",
  glyph: "sap-icon--table-view",
  sources: [
    {
      location: "/template-database-table/database.table.template",
      action: "generate",
      rename: "{{fileName}}.table",
    },
  ],
  parameters: [
    {
      name: "tableName",
      label: "Table Name",
    },
  ],
  order: 40,
});
