/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as daoTemplateManager from "template-application-dao-v2/template/template";
import * as generateUtils from "service-generate/template/generateUtils";
import * as parameterUtils from "service-generate/template/parameterUtils";

export function generate(model, parameters) {
    model = JSON.parse(model).model;
    const templateSources = getTemplate(parameters).sources;
    parameterUtils.process(model, parameters)
    return generateUtils.generateFiles(model, parameters, templateSources);
};

export function getTemplate(parameters) {
    const daoTemplate = daoTemplateManager.getTemplate(parameters);

    let templateSources = [{
        location: "/template-application-rest-v2/api/EntityController.ts.template",
        action: "generate",
        rename: "gen/{{genFolderName}}/api/{{perspectiveName}}/{{name}}Controller.ts",
        engine: "velocity",
        collection: "apiModels"
    }, {
        location: "/template-application-rest-v2/api/reportEntity.ts.template",
        action: "generate",
        rename: "gen/{{genFolderName}}/api/{{perspectiveName}}/{{name}}Service.ts",
        engine: "velocity",
        collection: "reportModels"
    }, {
        location: "/template-application-rest-v2/project.json.mjs",
        action: "generate",
        rename: "project.json",
        engine: "javascript"
    }];

    templateSources.push({
        location: "/template-application-rest-v2/roles/default-roles.roles.template",
        action: "generate",
        engine: "velocity",
        rename: "gen/{{genFolderName}}/roles/default-roles.roles"
    });

    templateSources = templateSources.concat(daoTemplate.sources);

    let templateParameters = [];
    templateParameters = templateParameters.concat(daoTemplate.parameters);

    return {
        name: "Application - REST - v2",
        description: "Application with REST APIs",
        extension: "model",
        sources: templateSources,
        parameters: templateParameters
    };
};
