/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.sdk.db;

import java.util.Set;

/**
 * Extension point through which the records referencing another record keep it from changing a
 * property they rely on (intent {@code checks: kind: agree [A, B] onProperty X} on a junction whose
 * parent is owned by another model, dirigible #7701).
 *
 * <p>
 * The junction's check runs when the junction row is written; afterwards the parent could change
 * {@code X} and leave the row in exactly the pairing the check refuses. A parent in the junction's
 * own model is guarded by its own generated repository. A parent owned by ANOTHER model cannot be:
 * its repository is generated by that model, which never reads this one's declarations - the same
 * direction problem {@link TargetDeleteRule} solves for deletes. So the REFERENCING side
 * contributes: its generated repository implements this interface, and every repository asks all
 * contributions on its update paths, refusing a change of a relied-on property with
 * {@link ValidationException} (400) carrying the check's own message. A contribution is a
 * {@code @Component} bean like any other extension, found through
 * {@link org.eclipse.dirigible.sdk.extensions.Extensions#find(Class)}.
 */
public interface TargetAgreementRule {

    /**
     * The properties of the given entity this contribution's records rely on - the only ones whose
     * change the target's repository has to ask about, so an update touching none of them costs
     * nothing.
     *
     * @param targetEntity the fully qualified class name of the entity being updated
     * @return the relied-on property names; empty when this contribution does not reference
     *         {@code targetEntity} at all
     */
    Set<String> agreedProperties(String targetEntity);

    /**
     * Whether a change of {@code property} on the given record is refused: a record of this
     * contribution references it and relies on that property.
     *
     * @param targetEntity the fully qualified class name of the entity being updated
     * @param targetId the primary key of the record being updated
     * @param property the property whose value the update changes
     * @return the refusal message, or {@code null} when nothing referencing the record relies on it
     */
    String refusal(String targetEntity, Object targetId, String property);
}
