/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.integration.tests.ui.tests;

import java.util.Map;

import org.eclipse.dirigible.tests.base.BaseTestProject;
import org.eclipse.dirigible.tests.base.ProjectUtil;
import org.eclipse.dirigible.tests.framework.browser.Browser;
import org.eclipse.dirigible.tests.framework.browser.HtmlAttribute;
import org.eclipse.dirigible.tests.framework.browser.HtmlElementType;
import org.eclipse.dirigible.tests.framework.ide.EdmView;
import org.eclipse.dirigible.tests.framework.ide.IDE;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 * Exercises the set of "Depends On" cascades over the sales-order model, but against the Alpine.js
 * + Harmonia SPA generated by {@code template-application-ui-harmonia-java} instead of the
 * AngularJS dashboard. The only fixture difference is the {@code templateId} in
 * {@code sales-order.gen}.
 * <p>
 * Each scenario is expressed through the deterministic auto-population the Harmonia depends-on
 * runtime performs: when a parent choice narrows a dependent dropdown to a single option that
 * option is auto-selected, and a dependent value field is copied straight in - so every assertion
 * is a positive check on the resulting value (no order-sensitive "must not exist" checks). The
 * dependent child forms are opened directly by their hash route (the same forms the master-detail
 * "Add" button navigates to); the FK to the master is irrelevant to the cascades under test, so it
 * is omitted.
 */
@Lazy
@Component
class DependsOnScenariosHarmoniaTestProject extends BaseTestProject {

    private static final String PROJECT_RESOURCES_PATH = "DependsOnScenariosHarmoniaTestProject";
    private static final String BASE_URI = "/services/web/DependsOnScenariosHarmoniaTestProject/gen/sales-order/index.html#";

    private final Browser browser;

    DependsOnScenariosHarmoniaTestProject(IDE ide, ProjectUtil projectUtil, EdmView edmView, Browser browser) {
        super(PROJECT_RESOURCES_PATH, ide, projectUtil, edmView);
        this.browser = browser;
    }

    @Override
    public void configure() {
        copyToWorkspace();
        generateEDM("sales-order.edm");
        publish();
    }

    @Override
    public void verify() {
        verifyCountryCityCascade();
        verifyProductUomAndPrice();
        verifyCustomerPaymentAndAmount();
        verifyRelatedCreateOpens();
    }

    /**
     * The FK "Add new" on a non-setting association must open the target entity's own create form in
     * the iframe dialog. Regression guard for the cross/self-model create URL: it was derived from the
     * Java controller URL and kept the Java-sanitized gen folder, so it 404'd for any hyphenated model
     * name (here {@code sales-order} -> {@code sales_order}). UoM is a non-setting association on
     * SalesOrderItem; clicking its "New UoM" opens the UoM create form (its "Name" field label proves
     * the form loaded rather than a 404 page). "UoM" matches only that button - the sidebar entry is
     * the humanized "Uo M".
     */
    private void verifyRelatedCreateOpens() {
        browser.openPath(BASE_URI + "/SalesOrderItem/create");
        browser.clickOnElementContainingText(HtmlElementType.BUTTON, "UoM");
        browser.assertElementExistsByTypeAndContainsText(HtmlElementType.SPAN, "Name");
    }

    /**
     * Customer form: City depends on Country. Each country has exactly one city, so it auto-selects.
     */
    private void verifyCountryCityCascade() {
        openCreateForm("/Customer");
        selectInCombobox("Select Country...", "Bulgaria");
        assertComboboxShows("Sofia");
        discardChanges();

        openCreateForm("/Customer");
        selectInCombobox("Select Country...", "Italy");
        assertComboboxShows("Rome");
        discardChanges();
    }

    /**
     * SalesOrderItem form: UoM (dropdown) and Price (number) both depend on Product. Choosing a product
     * narrows UoM to the product's single unit (auto-selected) and copies the product price.
     */
    private void verifyProductUomAndPrice() {
        openCreateForm("/SalesOrderItem");
        selectInCombobox("Select Product...", "Product A");
        assertComboboxShows("Kg");
        assertInputValue("f_Price", "11");
        discardChanges();

        openCreateForm("/SalesOrderItem");
        selectInCombobox("Select Product...", "Product B");
        assertComboboxShows("Liter");
        assertInputValue("f_Price", "20");
        discardChanges();
    }

    /**
     * SalesOrderPayment form: CustomerPayment (dropdown) depends on Customer and Amount (number)
     * depends on CustomerPayment. Each customer has exactly one payment, so choosing the customer
     * auto-selects the payment and, through it, copies the amount (a chained cascade).
     */
    private void verifyCustomerPaymentAndAmount() {
        openCreateForm("/SalesOrderPayment");
        selectInCombobox("Select Customer...", "Customer A");
        assertComboboxShows("Payment 1");
        assertInputValue("f_Amount", "101");
        discardChanges();

        openCreateForm("/SalesOrderPayment");
        selectInCombobox("Select Customer...", "Customer B");
        assertComboboxShows("Payment 2");
        assertInputValue("f_Amount", "201");
        discardChanges();
    }

    private void openCreateForm(String entityRoute) {
        browser.openPath(BASE_URI + entityRoute + "/create");
    }

    /**
     * Leave the form the scenario just filled in, the way a user does. Picking a value makes the form
     * dirty, and since dirigible #7359 an exit from a dirty form is vetoed and asks first - a hash
     * navigation to the next scenario's form included, because the SPA never leaves the document. So
     * each scenario ends on the guard dialog's Discard, which is also what keeps the scenarios
     * independent: the next one starts from a form the guard is not holding.
     * <p>
     * The dialog's Discard is addressed by its variant: while the form is dirty the footer Cancel is
     * relabelled "Discard" too, and only the dialog's is the negative one.
     */
    private void discardChanges() {
        browser.clickOnElementWithText(HtmlElementType.BUTTON, "Back to list");
        browser.clickOnElementByAttributePatternAndText("button", "data-variant", "negative", "Discard");
    }

    // Open an x-h-select by its placeholder (Harmonia hides the bound input and renders a visible
    // button[role="combobox"] trigger whose text is the placeholder) and click the option.
    private void selectInCombobox(String placeholder, String optionLabel) {
        browser.clickOnElementByAttributePatternAndText(HtmlElementType.BUTTON, HtmlAttribute.ROLE, "combobox", placeholder);
        browser.clickOnElementByAttributePatternAndText(HtmlElementType.DIV, HtmlAttribute.ROLE, "option", optionLabel);
    }

    // A retrying assertion (Condition.exactText) - also the synchronization point that lets the async
    // cascade settle before the subsequent, non-retrying input-value assertion runs.
    private void assertComboboxShows(String value) {
        browser.assertElementExistByAttributePatternAndText(HtmlElementType.BUTTON, HtmlAttribute.ROLE, "combobox", value);
    }

    private void assertInputValue(String inputId, String value) {
        browser.assertElementValueByAttributes(HtmlElementType.INPUT, Map.of(HtmlAttribute.ID, inputId), value);
    }
}
