/*
 * Copyright (c) 2010-2026 Eclipse Dirigible contributors
 *
 * All rights reserved. This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-FileCopyrightText: Eclipse Dirigible contributors SPDX-License-Identifier: EPL-2.0
 */
package org.eclipse.dirigible.integration.tests.ui.tests;

import org.eclipse.dirigible.tests.base.BaseTestProject;
import org.eclipse.dirigible.tests.base.ProjectUtil;
import org.eclipse.dirigible.tests.framework.browser.Browser;
import org.eclipse.dirigible.tests.framework.browser.HtmlAttribute;
import org.eclipse.dirigible.tests.framework.browser.HtmlElementType;
import org.eclipse.dirigible.tests.framework.ide.EdmView;
import org.eclipse.dirigible.tests.framework.ide.IDE;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;

/**
 * Exercises the "Depends On" scenario (a City dropdown that is filtered by the selected Country),
 * but against the modern Alpine.js + Harmonia SPA generated by the
 * {@code template-application-ui-harmonia-java} full-stack template instead of the legacy AngularJS
 * dashboard. The only difference from the AngularJS fixture is the {@code templateId} in
 * {@code edm.gen}; the model, data and depends-on metadata are identical.
 */
@Lazy
@Component
class DependsOnHarmoniaTestProject extends BaseTestProject {

    private static final String EDM_FILE_NAME = "edm.edm";
    private static final String PROJECT_RESOURCES_PATH = "DependsOnHarmoniaIT";

    // The Harmonia SPA entry (per-project shell), hash-routed by Pinecone. Open the Orders create
    // route directly to avoid the dashboard's ambiguous entity tiles.
    private static final String ORDERS_LIST_URI = "/services/web/DependsOnHarmoniaIT/gen/edm/index.html#/Orders";

    private final Browser browser;

    DependsOnHarmoniaTestProject(IDE ide, ProjectUtil projectUtil, EdmView edmView, Browser browser) {
        super(PROJECT_RESOURCES_PATH, ide, projectUtil, edmView);
        this.browser = browser;
    }

    @Override
    public void configure() {
        copyToWorkspace();
        generateEDM(EDM_FILE_NAME);
        publish();
    }

    @Override
    public void verify() {
        browser.openPath(ORDERS_LIST_URI);

        // Open the Orders create form via the list toolbar's primary "New" button (the Harmonia
        // equivalent of the AngularJS "Create" button).
        browser.clickOnElementWithText(HtmlElementType.BUTTON, "New");

        // The form caption is the entity's human label - assert the generator DERIVED it (the
        // depends-on entities are hand-authored, so they carry no baked entityLabel) rather than
        // leaking the literal "${ENTITYLABEL}" placeholder. We assert the placeholder is ABSENT
        // rather than asserting the resolved text is present: the entity is named "Orders", so its
        // derived entityLabel (the form caption) equals its menuLabel (the list toolbar title), and
        // both render as unified caption <span>s since #6361 - so "one span contains Orders" is
        // inherently ambiguous (two matches, which the ExistsByTypeAndContainsText finder rejects).
        // The placeholder-absent check is the real intent; the form's rendering and label resolution
        // are further proven by the Country/City depends-on assertions below.
        browser.assertElementDoesNotExistsByTypeAndContainsText(HtmlElementType.SPAN, "${ENTITYLABEL}");

        // Pick Country = Bulgaria. The Harmonia x-h-select hides the bound <input id="f_Country">
        // and renders a visible <button role="combobox"> trigger (a span until Harmonia 2.12) whose
        // text is the placeholder; click that trigger, then the option (a div[role="option"] whose
        // text is the label).
        browser.clickOnElementByAttributePatternAndText(HtmlElementType.BUTTON, HtmlAttribute.ROLE, "combobox", "Select Country...");
        browser.clickOnElementByAttributePatternAndText(HtmlElementType.DIV, HtmlAttribute.ROLE, "option", "Bulgaria");

        // The selection now shows on the Country trigger - this is also what fires the depends-on
        // watcher that re-filters the City options.
        browser.assertElementExistByAttributePatternAndText(HtmlElementType.BUTTON, HtmlAttribute.ROLE, "combobox", "Bulgaria");

        verifyUnsavedChangesGuard();

        // City depends on Country: opening it now must offer only Bulgaria's cities. The offered
        // options are asserted on the option element itself, not on a <span>: since Harmonia 2.7 an
        // option renders its label inside a text COLUMN (a span wrapping the label span, so a
        // description can sit under it), so a bare "one span contains Sofia" is two matches - which
        // the ExistsByTypeAndContainsText finder rejects. div[role="option"] is the stable anchor,
        // and it is what the Country selection above already clicks.
        browser.clickOnElementByAttributePatternAndText(HtmlElementType.BUTTON, HtmlAttribute.ROLE, "combobox", "Select City...");
        browser.assertElementExistByAttributePatternAndText(HtmlElementType.DIV, HtmlAttribute.ROLE, "option", "Sofia");
        browser.assertElementExistByAttributePatternAndText(HtmlElementType.DIV, HtmlAttribute.ROLE, "option", "Varna");
        browser.assertElementDoesNotExistsByTypeAndContainsText(HtmlElementType.SPAN, "Milano");
    }

    /**
     * The unsaved-changes guard (dirigible #7359), on the form the user is standing on.
     *
     * <p>
     * Until it existed every exit from an edited form - Back to list, Cancel, a sidebar entry, the
     * browser's own Back button - dropped the edit without a word, and nothing in the page said the
     * form was dirty at all. The mechanism lives in the SHARED runtime (basePage snapshots the save
     * payload, App.leaveGuard vetoes the route change) and is wired into every generated form, so it
     * can only be proven in a browser: a snapshot taken at the wrong moment, a member Alpine cannot
     * resolve in the view's scope, or a dialog Harmonia never opens all render as a page that looks
     * exactly right and still loses the edit.
     *
     * <p>
     * The picked Country is a real change against the create-mode snapshot, so at this point the form
     * is dirty. Keep editing must leave it exactly as it was - which is the whole point of asking.
     */
    private void verifyUnsavedChangesGuard() {
        browser.assertElementExistsByTypeAndContainsText(HtmlElementType.SPAN, "Unsaved changes");

        browser.clickOnElementWithText(HtmlElementType.BUTTON, "Back to list");

        // The dialog, not the list: the exit was vetoed and the user is being asked.
        browser.assertElementExistsByTypeAndContainsText("h2", "Unsaved changes");
        browser.assertElementExistsByTypeAndContainsText(HtmlElementType.SPAN, "Save and leave");
        browser.clickOnElementWithText(HtmlElementType.BUTTON, "Keep editing");

        // Still on the form, and the edit is still there.
        browser.assertElementExistByAttributePatternAndText(HtmlElementType.BUTTON, HtmlAttribute.ROLE, "combobox", "Bulgaria");
    }
}
