/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */
import * as generateUtils from "service-generate/template/generateUtils";
import * as parameterUtils from "service-generate/template/parameterUtils";

export function generate(model, parameters) {
    model = JSON.parse(model).model;
    let templateSources = getTemplate(parameters).sources;
    parameterUtils.process(model, parameters)
    return generateUtils.generateFiles(model, parameters, templateSources);
};

export function getTemplate(parameters) {
    return {
        name: "Application - DAO - v2",
        description: "Application with DAO",
        extension: "model",
        sources: [
            {
                location: "/template-application-dao-v2/data/Repository.ts.template",
                action: "generate",
                rename: "gen/{{genFolderName}}/data/{{perspectiveName}}/{{name}}Repository.ts",
                engine: "velocity",
                collection: "daoModels"
            },
            {
                location: "/template-application-dao-v2/data/Entity.ts.template",
                action: "generate",
                rename: "gen/{{genFolderName}}/data/{{perspectiveName}}/{{name}}Entity.ts",
                engine: "velocity",
                collection: "daoModels"
            },
            {
                location: "/template-application-dao-v2/data/entity.extensionpoint.template",
                action: "generate",
                rename: "gen/{{genFolderName}}/data/{{perspectiveName}}/{{name}}.extensionpoint",
                engine: "velocity",
                collection: "daoModels"
            },
            {
                location: "/template-application-dao-v2/data/reportEntity.ts.template",
                action: "generate",
                rename: "gen/{{genFolderName}}/data/{{perspectiveName}}/{{name}}Repository.ts",
                engine: "velocity",
                collection: "reportModels"
            },
            {
                location: "/template-application-dao-v2/project.json.mjs",
                action: "generate",
                rename: "project.json",
                engine: "javascript",
            }
        ],
        parameters: [
            {
                name: "tablePrefix",
                label: "Table Prefix",
                placeholder: "Table prefix",
                required: false
            },
            {
                name: "dataSource",
                label: "Data Source",
                placeholder: "Data Source (DefaultDB)",
                required: false
            }
        ]
    };
};
