/*
 * Generated by Eclipse Dirigible based on model and template.
 *
 * Do not modify the content as it may be re-generated again.
 */

export function getSources(parameters) {
    const sources = [];

    sources.push(...getTableReportBackendSources());
    sources.push(...getTableReportUISource());

    return sources;
};

function getTableReportBackendSources() {
    return [
        {
            location: "/template-application-dao/dao/reportFileEntity.ts.template",
            action: "generate",
            rename: "gen/{{genFolderName}}/dao/Reports/{{name}}Repository.ts",
            engine: "velocity",
            collection: "reportModels"
        },
        {
            location: "/template-application-rest/api/utils/HttpUtils.ts.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/api/utils/HttpUtils.ts",
        }, {
            location: "/template-application-rest/api/utils/ForbiddenError.ts.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/api/utils/ForbiddenError.ts",
        }, {
            location: "/template-application-rest/api/utils/ValidationError.ts.template",
            action: "copy",
            rename: "gen/{{genFolderName}}/api/utils/ValidationError.ts",
        }, {
            location: "/template-application-rest/api/reportFileEntity.ts.template",
            action: "generate",
            rename: "gen/{{genFolderName}}/api/Reports/{{name}}Service.ts",
            engine: "velocity",
            collection: "reportModels"
        }, {
            location: "/template-application-rest/roles/default-roles.roles.template",
            action: "generate",
            rename: "gen/{{genFolderName}}/roles/default-roles.roles",
            engine: "velocity",
            collection: "reportModels"
        }, {
            location: "/template-application-rest/project.json.mjs",
            action: "generate",
            rename: "project.json",
            engine: "javascript"
        }, {
            location: "/template-application-rest/tsconfig.json.template",
            action: "generate",
            rename: "tsconfig.json",
            engine: "velocity"
        }
    ];
}

function getTableReportUISource() {
    return [
        {
            location: "/template-application-ui-angular/ui/translations-report.json.template",
            action: "translate",
        },
        // Location: "gen/{{genFolderName}}/ui/perspective/list"
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-window/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-window/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-window/view.extension.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/view.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-window/view.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-window/view.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-filter/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-filter/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-filter/view.extension.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/view.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-filter/view.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-filter/view.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/view.extension.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/view.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/view.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/view.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-print/controller.js.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/controller.js",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-print/index.html.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/index.html",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-print/print.extension.template",
            action: "generate",
            engine: "velocity",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/print.extension",
            collection: "generateReportModels"
        },
        {
            location: "/template-application-ui-angular/ui/perspective/report-file/dialog-print/print.js.template",
            action: "generate",
            rename: "gen/{{genFolderName}}/ui/Reports/{{name}}/dialog-print/print.js",
            collection: "generateReportModels"
        }];
}